# Fan Control Signals
set_property PACKAGE_PIN N21 [get_ports {fan_tach_in_tri_i[0]}]
set_property PACKAGE_PIN T24 [get_ports {fan_pwm_out[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {fan_tach_in_tri_i[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {fan_pwm_out[0]}]

# LPDDR4 PINOUT
set_property PACKAGE_PIN AE17 [get_ports {ch0_lpddr4_trip1_ca_a[1]}]
set_property PACKAGE_PIN AE18 [get_ports ch0_lpddr4_trip1_cke_a]
set_property PACKAGE_PIN AE13 [get_ports {ch0_lpddr4_trip1_ca_a[5]}]
set_property PACKAGE_PIN AE14 [get_ports {ch0_lpddr4_trip1_ca_a[2]}]
set_property PACKAGE_PIN AD16 [get_ports ch0_lpddr4_trip1_ck_t_a]
set_property PACKAGE_PIN AD15 [get_ports ch0_lpddr4_trip1_ck_c_a]
set_property PACKAGE_PIN AB21 [get_ports {ch0_lpddr4_trip1_dq_a[0]}]
set_property PACKAGE_PIN AC22 [get_ports {ch0_lpddr4_trip1_dq_a[7]}]
set_property PACKAGE_PIN AB20 [get_ports {ch0_lpddr4_trip1_dq_a[6]}]
set_property PACKAGE_PIN AC20 [get_ports {ch0_lpddr4_trip1_dq_a[1]}]
set_property PACKAGE_PIN AB18 [get_ports {ch0_lpddr4_trip1_dqs_t_a[0]}]
set_property PACKAGE_PIN AB17 [get_ports {ch0_lpddr4_trip1_dqs_c_a[0]}]
set_property PACKAGE_PIN AB15 [get_ports {ch0_lpddr4_trip1_dq_a[2]}]
set_property PACKAGE_PIN AC16 [get_ports {ch0_lpddr4_trip1_dq_a[3]}]
set_property PACKAGE_PIN AB14 [get_ports {ch0_lpddr4_trip1_dq_a[5]}]
set_property PACKAGE_PIN AC13 [get_ports {ch0_lpddr4_trip1_dq_a[4]}]
set_property PACKAGE_PIN AB12 [get_ports {ch0_lpddr4_trip1_dmi_a[0]}]
set_property PACKAGE_PIN AC11 [get_ports {ch0_lpddr4_trip1_ca_a[4]}]
set_property PACKAGE_PIN AD22 [get_ports {ch0_lpddr4_trip1_dq_a[9]}]
set_property PACKAGE_PIN AE22 [get_ports {ch0_lpddr4_trip1_dq_a[8]}]
set_property PACKAGE_PIN AD20 [get_ports {ch0_lpddr4_trip1_dq_a[15]}]
set_property PACKAGE_PIN AD21 [get_ports {ch0_lpddr4_trip1_dq_a[10]}]
set_property PACKAGE_PIN AC19 [get_ports {ch0_lpddr4_trip1_dmi_a[1]}]
set_property PACKAGE_PIN AD19 [get_ports {ch0_lpddr4_trip1_ca_a[3]}]
set_property PACKAGE_PIN AC17 [get_ports {ch0_lpddr4_trip1_dq_a[14]}]
set_property PACKAGE_PIN AD17 [get_ports {ch0_lpddr4_trip1_dq_a[13]}]
set_property PACKAGE_PIN AC14 [get_ports {ch0_lpddr4_trip1_dq_a[11]}]
set_property PACKAGE_PIN AD14 [get_ports {ch0_lpddr4_trip1_dq_a[12]}]
set_property PACKAGE_PIN AD12 [get_ports {ch0_lpddr4_trip1_dqs_t_a[1]}]
set_property PACKAGE_PIN AD11 [get_ports {ch0_lpddr4_trip1_dqs_c_a[1]}]
set_property PACKAGE_PIN AE19 [get_ports {ch0_lpddr4_trip1_dq_b[5]}]
set_property PACKAGE_PIN AF19 [get_ports {ch0_lpddr4_trip1_dq_b[4]}]
set_property PACKAGE_PIN AF18 [get_ports {ch0_lpddr4_trip1_dq_b[2]}]
set_property PACKAGE_PIN AG18 [get_ports {ch0_lpddr4_trip1_dq_b[3]}]
set_property PACKAGE_PIN AG17 [get_ports {ch0_lpddr4_trip1_dqs_t_b[0]}]
set_property PACKAGE_PIN AG16 [get_ports {ch0_lpddr4_trip1_dqs_c_b[0]}]
set_property PACKAGE_PIN AF14 [get_ports {ch0_lpddr4_trip1_dq_b[6]}]
set_property PACKAGE_PIN AG15 [get_ports {ch0_lpddr4_trip1_dq_b[1]}]
set_property PACKAGE_PIN AF13 [get_ports {ch0_lpddr4_trip1_dq_b[0]}]
set_property PACKAGE_PIN AG13 [get_ports {ch0_lpddr4_trip1_dq_b[7]}]
set_property PACKAGE_PIN AG12 [get_ports {ch0_lpddr4_trip1_dmi_b[0]}]
set_property PACKAGE_PIN AG11 [get_ports ch0_lpddr4_trip1_cs_a]
set_property PACKAGE_PIN AG22 [get_ports {ch0_lpddr4_trip1_dq_b[9]}]
set_property PACKAGE_PIN AH22 [get_ports {ch0_lpddr4_trip1_dq_b[8]}]
set_property PACKAGE_PIN AG21 [get_ports {ch0_lpddr4_trip1_dq_b[10]}]
set_property PACKAGE_PIN AH20 [get_ports {ch0_lpddr4_trip1_dq_b[11]}]
set_property PACKAGE_PIN AG20 [get_ports {ch0_lpddr4_trip1_dqs_t_b[1]}]
set_property PACKAGE_PIN AH19 [get_ports {ch0_lpddr4_trip1_dqs_c_b[1]}]
set_property PACKAGE_PIN AH17 [get_ports {ch0_lpddr4_trip1_dq_b[13]}]
set_property PACKAGE_PIN AH18 [get_ports {ch0_lpddr4_trip1_dq_b[12]}]
set_property PACKAGE_PIN AH14 [get_ports {ch0_lpddr4_trip1_dq_b[14]}]
set_property PACKAGE_PIN AH15 [get_ports {ch0_lpddr4_trip1_dq_b[15]}]
set_property PACKAGE_PIN AH13 [get_ports {ch0_lpddr4_trip1_dmi_b[1]}]
set_property PACKAGE_PIN AH12 [get_ports {ch0_lpddr4_trip1_ca_a[0]}]

# AMD/Xilinx Answer Record 35358 (Change LPDDR4 RESET_N / SYSCLK 
# Voltage Standard Conflict for Pin Efficient Topologies
# TCL COMMAND NEEDED: set_property -dict [list CONFIG.MC_LP4_OVERWRITE_IO_PROP {true}] [get_bd_cells axi_noc_0]
set_property PACKAGE_PIN L25 [get_ports ch0_lpddr4_trip1_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports ch0_lpddr4_trip1_reset_n]

set_property PACKAGE_PIN AB27 [get_ports ch1_lpddr4_trip1_cke_a]
set_property PACKAGE_PIN AC27 [get_ports {ch1_lpddr4_trip1_ca_a[0]}]
set_property PACKAGE_PIN AC24 [get_ports {ch1_lpddr4_trip1_ca_a[5]}]
set_property PACKAGE_PIN AC25 [get_ports {ch1_lpddr4_trip1_ca_a[3]}]
set_property PACKAGE_PIN AB23 [get_ports ch1_lpddr4_trip1_ck_t_a]
set_property PACKAGE_PIN AC23 [get_ports ch1_lpddr4_trip1_ck_c_a]
set_property PACKAGE_PIN AA26 [get_ports {ch1_lpddr4_trip1_dq_b[15]}]
set_property PACKAGE_PIN AB26 [get_ports {ch1_lpddr4_trip1_dq_b[8]}]
set_property PACKAGE_PIN AA28 [get_ports {ch1_lpddr4_trip1_dq_b[13]}]
set_property PACKAGE_PIN AB28 [get_ports {ch1_lpddr4_trip1_dq_b[9]}]
set_property PACKAGE_PIN Y28 [get_ports {ch1_lpddr4_trip1_dmi_b[1]}]
set_property PACKAGE_PIN Y27 [get_ports ch1_lpddr4_trip1_cs_a]
set_property PACKAGE_PIN W27 [get_ports {ch1_lpddr4_trip1_dq_b[11]}]
set_property PACKAGE_PIN Y26 [get_ports {ch1_lpddr4_trip1_dq_b[14]}]
set_property PACKAGE_PIN V25 [get_ports {ch1_lpddr4_trip1_dq_b[10]}]
set_property PACKAGE_PIN W26 [get_ports {ch1_lpddr4_trip1_dq_b[12]}]
set_property PACKAGE_PIN V28 [get_ports {ch1_lpddr4_trip1_dqs_t_b[1]}]
set_property PACKAGE_PIN V27 [get_ports {ch1_lpddr4_trip1_dqs_c_b[1]}]
set_property PACKAGE_PIN Y22 [get_ports {ch1_lpddr4_trip1_dq_a[6]}]
set_property PACKAGE_PIN AA21 [get_ports {ch1_lpddr4_trip1_dq_a[7]}]
set_property PACKAGE_PIN Y23 [get_ports {ch1_lpddr4_trip1_dq_a[3]}]
set_property PACKAGE_PIN AA22 [get_ports {ch1_lpddr4_trip1_dq_a[0]}]
set_property PACKAGE_PIN Y24 [get_ports {ch1_lpddr4_trip1_dqs_t_a[0]}]
set_property PACKAGE_PIN AA23 [get_ports {ch1_lpddr4_trip1_dqs_c_a[0]}]
set_property PACKAGE_PIN V24 [get_ports {ch1_lpddr4_trip1_dq_a[2]}]
set_property PACKAGE_PIN W25 [get_ports {ch1_lpddr4_trip1_dq_a[4]}]
set_property PACKAGE_PIN V23 [get_ports {ch1_lpddr4_trip1_dq_a[1]}]
set_property PACKAGE_PIN W24 [get_ports {ch1_lpddr4_trip1_dq_a[5]}]
set_property PACKAGE_PIN V22 [get_ports {ch1_lpddr4_trip1_dmi_a[0]}]
set_property PACKAGE_PIN W21 [get_ports {ch1_lpddr4_trip1_ca_a[4]}]
set_property PACKAGE_PIN AG26 [get_ports {ch1_lpddr4_trip1_dq_b[7]}]
set_property PACKAGE_PIN AG27 [get_ports {ch1_lpddr4_trip1_dq_b[0]}]
set_property PACKAGE_PIN AG28 [get_ports {ch1_lpddr4_trip1_dq_b[1]}]
set_property PACKAGE_PIN AH27 [get_ports {ch1_lpddr4_trip1_dq_b[6]}]
set_property PACKAGE_PIN AE28 [get_ports {ch1_lpddr4_trip1_dmi_b[0]}]
set_property PACKAGE_PIN AF28 [get_ports {ch1_lpddr4_trip1_ca_a[1]}]
set_property PACKAGE_PIN AE27 [get_ports {ch1_lpddr4_trip1_dq_b[2]}]
set_property PACKAGE_PIN AF26 [get_ports {ch1_lpddr4_trip1_dq_b[5]}]
set_property PACKAGE_PIN AD26 [get_ports {ch1_lpddr4_trip1_dq_b[3]}]
set_property PACKAGE_PIN AE26 [get_ports {ch1_lpddr4_trip1_dq_b[4]}]
set_property PACKAGE_PIN AC28 [get_ports {ch1_lpddr4_trip1_dqs_t_b[0]}]
set_property PACKAGE_PIN AD27 [get_ports {ch1_lpddr4_trip1_dqs_c_b[0]}]
set_property PACKAGE_PIN AH24 [get_ports {ch1_lpddr4_trip1_dq_a[12]}]
set_property PACKAGE_PIN AH25 [get_ports {ch1_lpddr4_trip1_dq_a[10]}]
set_property PACKAGE_PIN AG23 [get_ports {ch1_lpddr4_trip1_dq_a[9]}]
set_property PACKAGE_PIN AH23 [get_ports {ch1_lpddr4_trip1_dq_a[11]}]
set_property PACKAGE_PIN AF24 [get_ports {ch1_lpddr4_trip1_dqs_t_a[1]}]
set_property PACKAGE_PIN AF23 [get_ports {ch1_lpddr4_trip1_dqs_c_a[1]}]
set_property PACKAGE_PIN AF25 [get_ports {ch1_lpddr4_trip1_dq_a[14]}]
set_property PACKAGE_PIN AG25 [get_ports {ch1_lpddr4_trip1_dq_a[13]}]
set_property PACKAGE_PIN AD25 [get_ports {ch1_lpddr4_trip1_dq_a[15]}]
set_property PACKAGE_PIN AE24 [get_ports {ch1_lpddr4_trip1_dq_a[8]}]
set_property PACKAGE_PIN AD24 [get_ports {ch1_lpddr4_trip1_dmi_a[1]}]
set_property PACKAGE_PIN AE23 [get_ports {ch1_lpddr4_trip1_ca_a[2]}]

# AMD/Xilinx Answer Record 35358 (Change LPDDR4 RESET_N / SYSCLK 
# Voltage Standard Conflict for Pin Efficient Topologies
# TCL COMMAND NEEDED: set_property -dict [list CONFIG.MC_LP4_OVERWRITE_IO_PROP {true}] [get_bd_cells axi_noc_0]
set_property PACKAGE_PIN L24 [get_ports ch1_lpddr4_trip1_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports ch1_lpddr4_trip1_reset_n]

set_property PACKAGE_PIN N23 [get_ports lpddr4_clk1_clk_p]
set_property PACKAGE_PIN N24 [get_ports lpddr4_clk1_clk_n]

# AMD/Xilinx Answer Record 35358 (Change LPDDR4 RESET_N / SYSCLK 
# Voltage Standard Conflict for Pin Efficient Topologies
# TCL COMMAND NEEDED: set_property -dict [list CONFIG.MC_LP4_OVERWRITE_IO_PROP {true}] [get_bd_cells axi_noc_0]
set_property IOSTANDARD LVDS15 [get_ports lpddr4_clk1_clk_p]
set_property IOSTANDARD LVDS15 [get_ports lpddr4_clk1_clk_n]